development:
  forest_env_secret: a417dafff0efe7fba8a125c4ee4b3809a2c54d55f31fa1c5a016baa7b163ef5b
  forest_auth_secret: LzKpvKR9krzfhkeCmSTlRQ
  forest_application_url: http://localhost:3000
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  forest_application_url: <%= ENV["FOREST_APPLICATION_URL"] %>
